[build]
builder = "nixpacks"

[deploy]
startCommand = "uvicorn minimal_app:app --host 0.0.0.0 --port $PORT --log-level info"
healthcheckPath = "/health"
healthcheckTimeout = 300
restartPolicyType = "on_failure"

[build.env]
NIXPACKS_PYTHON_VERSION = "3.11"

[variables]
PYTHONPATH = "/app"
